# Generated by Django 5.0.6 on 2025-12-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('F', 'F'), ('IP', 'In Progress'), ('W', 'Withdrawn')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Marks out of 100', max_digits=5, null=True),
        ),
    ]
