# Generated by Django 5.0.6 on 2025-12-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('MATH', 'Mathematics'), ('ENG', 'Engineering'), ('BUS', 'Business'), ('SCI', 'Science'), ('ART', 'Arts'), ('MED', 'Medicine'), ('LAW', 'Law'), ('EDU', 'Education'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
    ]
